[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
lib_ldf_mode = deep
lib_extra_dirs = ../../
monitor_speed = 115200
upload_speed = 921600

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_ldf_mode = deep
lib_extra_dirs = ../../
monitor_speed = 115200
upload_speed = 921600
